server:
  port: 9999
  undertow:
    accesslog:
      dir: ./logs
  tomcat:
    accesslog:
      directory: ./logs2
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/learnjdbc?serverTimezone=UTC
    username: learn
    password: learnpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3 # seconds