server:
  port: 9999
  undertow:
    accesslog:
      dir: ./logs
  tomcat:
    accesslog:
      directory: ./logs2
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/learnjdbc?serverTimezone=UTC
    username: learn
    password: learnpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      filters: stat,wall #stat监控统计,wall防火墙
      filter: #配置具体的filter
        stat:
          slow-sql-millis: 1000 #慢查询时间
        wall:
          enabled: true
          config:
            drop-table-allow: false #是否允许删除表
  jdbc:
    template:
      query-timeout: 3 # seconds
  redis:
    url: redis://localhost:6379/0
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

management:
  endpoints:
    enabled-by-default: true # 默认开启所有监控端点
    web:
      exposure:
          include: "*" # 以web方式暴露所有监控端点
  endpoint:
    health:
      show-details: always # 显示健康检查的全部细节
info:
  appName: boot-admin
  appVersion: 1.0.0
  mavenProjectName: @project.name@
  mavenProjectVersion: @project.version@
