server:
  port: 9999
  undertow:
    accesslog:
      dir: ./logs
  tomcat:
    accesslog:
      directory: ./logs2
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB